config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # mount Rswag::Ui::Engine => '/api-docs'
  # mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
                     :authorized_applications
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :api, defaults: { format: 'json' } do
    resources :items
  end

  resources :products

  get 'data_license', to: 'home#data_license'
  get 'documentation', to: 'home#documentation'
  get 'acknowledgements', to: 'home#acknowledgements'

  root to: 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord # rubocop:disable Style/Documentation
  has_paper_trail

  validates :gtin, presence: true, uniqueness: true
  validates :name, presence: true

  def self.from_param(param)
    by_gtin(param)&.first
  end

  def to_param
    gtin
  end

  scope :full_text_search, lambda { |terms|
    where(
      [
        FULL_TEXT_SEARCH_SQL,
        { terms: map_search_terms(terms) }
      ]
    )
  }

  scope :by_gtin, lambda { |gtin|
    where(gtin: padded_gtins(gtin))
  }

  FULL_TEXT_SEARCH_SQL = <<~SQL.squish
    to_tsvector('english', products.properties) @@ to_tsquery(:terms)
    OR to_tsvector('english', products.name) @@ to_tsquery(:terms)
    OR to_tsvector('english', products.brand_name) @@ to_tsquery(:terms)
  SQL

  private_constant :FULL_TEXT_SEARCH_SQL

  class << self
    def map_search_terms(terms)
      Array
        .wrap(terms)
        .map { |term| "#{sanitize_term(term)}:*" }
        .join(' & ')
    end

    def padded_gtins(gtin)
      return [gtin] if gtin.length == 14 && gtin[0] != '0'

      gtin_14 = gtin.rjust(14, '0') # rubocop:disable Naming/VariableNumber
      gtin_13 = gtin_14.slice(1, 13) # rubocop:disable Naming/VariableNumber

      [gtin_14, gtin_13, gtin]
    end

    def sanitize_term(term)
      term.gsub(/([^a-zA-Z0-9 -])/, '\\\\\\1')
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Controller for products
class ProductsController < ApplicationController
  include ProductSearch

  before_action :authenticate_user!, except: %i[index show destroy]
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @pagy, @products = product_search(params)
  end

  def show # rubocop:disable Metrics/MethodLength
    if @product.nil?
      respond_to do |format|
        format.html { redirect_to products_path, alert: 'Product not found' } # rubocop:disable Rails/I18nLocaleTexts
        format.json { render json: { error: 'Product not found' }, status: :not_found }
      end
    else
      respond_to do |format|
        format.html
        format.json
      end
    end
  end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.' # rubocop:disable Rails/I18nLocaleTexts
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.' # rubocop:disable Rails/I18nLocaleTexts
    else
      render :edit
    end
  end

  def destroy
    raise 'Not implemented'
  end

  private

  # SMELL: Not used?
  def flatten_product_attributes(product)
    product
      .attributes
      .slice(*%w[gtin name brand_name])
      .merge(product.properties)
      .compact
  end

  # SMELL: Not used?
  def set_product
    @product = Product.from_param(params[:id])
  end

  def product_params # rubocop:disable Metrics/MethodLength
    params
      .expect(
        product: [:gtin,
                  :name,
                  :brand_name,
                  { properties: {} }]
      ).tap do |permitted_params|
        permitted_params[:properties].each_key do |key|
          permitted_params[:properties].delete(key) if permitted_params[:properties][key].blank?
        end
      end
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper # rubocop:disable Style/Documentation
  def humanize_product_count(product_count)
    [
      number_with_delimiter(product_count),
      'product'.pluralize(product_count)
    ].join(' ')
  end

  def unit_for_property(key)
    PropertySet::ALL.dig(key.to_sym, :unit) || ''
  end

  def title_for_property(key)
    PropertySet::ALL.dig(key.to_sym, :title) || key.to_s.humanize
  end

  def type_for_property(key)
    PropertySet::ALL.dig(key.to_sym, :type) || 'text'
  end

  def link_to_property_set(title, target)
    link_to(
      title,
      nil,
      class: 'property-set-link ml-3 mt-3 inline-flex items-center rounded-md border border-transparent bg-orange-600 px-2 py-1 text-sm font-small text-white shadow-sm hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-2', # rubocop:disable Layout/LineLength
      data: { target: }
    )
  end
end

app/views/products/_form.html.erb
<div class="column is-6 is-offset-2" data-controller="properties">
  <%= form_with(model: product, data: { turbo: false }) do |form| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <label class="label is-small">GTIN</label>
      <div class="control">
        <%= form.text_field :gtin, class: 'input is-small', disabled: product.persisted? %>
      </div>
    </div>

    <div class="field">
      <label class="label is-small">Brand</label>
      <div class="control">
        <%= form.text_field :brand_name, class: 'input is-small' %>
      </div>
    </div>

    <div class="field">
      <label class="label is-small">Name</label>
      <div class="control">
        <%= form.text_field :name, class: 'input is-small' %>
      </div>
    </div>

    <% (product.properties.keys.map(&:to_sym) - PropertySet::ALL.keys).each do |key| %>
      <%= render 'property_field', product: product, key: key %>
    <%- end -%>

    <section>
      <%- if PropertySet::NUTRITION_FACTS.keys.none? { |key| product.properties[key.to_s].present? } -%>
        <%= link_to_property_set('Add nutrition facts', 'nutrition-facts') %>
      <%- end -%>

      <div id="nutrition-facts">
        <h3>Nutrition Facts</h3>
        <% PropertySet::NUTRITION_FACTS.keys.each do |key| %>
          <%= render 'property_field', product: product, key: key %>
        <%- end -%>
      </div>
    </section>

    <section>
      <%- if PropertySet::INGREDIENTS.keys.none? { |key| product.properties[key.to_s].present? } -%>
        <%= link_to_property_set('Add ingredients', 'ingredients') %>
      <%- end -%>

      <div id="ingredients">
        <h3>Ingredients</h3>
        <% PropertySet::INGREDIENTS.keys.each do |key| %>
          <%= render 'property_field', product: product, key: key %>
        <%- end -%>
      </div>
    </section>

    <section>
      <%- if PropertySet::PUBLISHING_DETAILS.keys.none? { |key| product.properties[key.to_s].present? } -%>
        <%= link_to_property_set('Add publishing details', 'publishing-details') %>
      <%- end -%>

      <div id="publishing-details">
        <h3>Publishing Details</h3>
        <% PropertySet::PUBLISHING_DETAILS.keys.each do |key| %>
          <%= render 'property_field', product: product, key: key %>
        <%- end -%>
      </div>
    </section>

    <section>
      <%- if PropertySet::PACK_DETAILS.keys.none? { |key| product.properties[key.to_s].present? } -%>
        <%= link_to_property_set('Add pack details', 'pack_details') %>
      <%- end -%>

      <div id="pack_details">
        <h3>Pack Details</h3>
        <% PropertySet::PACK_DETAILS.keys.each do |key| %>
          <%= render 'property_field', product: product, key: key %>
        <%- end -%>
      </div>
    </section>

    <div class="actions mt-3">
      <%= form.submit class: "inline-flex items-center rounded-md border border-transparent bg-orange-600 px-4 py-2 text-base font-medium text-white hover:bg-orange-700" %>
    </div>

    <p>
    By submitting changes, you agree to release your contribution
    under <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank">CC0 1.0 Universal</a>
    </p>
  <% end %>
</div>

app/views/products/_property_field.html.erb
<% unit = unit_for_property(key) %>

<div class="field">
  <label class="label is-small"><%= title_for_property(key) %></label>
  <div class="control <%= 'has-icons-right' if unit.present? %>">
    <input
      name="product[properties][<%= key %>]"
      type=<%= type_for_property(key) %>
      value="<%= product.properties[key.to_s] %>"
      class="input is-small"
    />
    <% if unit.present? %>
      <span class="icon is-small is-right">
        <%= unit %>
      </span>
    <%- end -%>
  </div>
</div>

app/views/products/_search_form.html.erb
<%= form_tag(products_path, method: :get) do %>
  Search <%= text_field_tag :query %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/products/edit.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6">
  <div class="bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:p-6">
      <div class="sm:flex sm:items-start sm:justify-between">
        <div>
          <h3 class="text-lg font-medium leading-6 text-gray-900"><%= @product.name %></h3>
          <div class="mt-2 max-w-xl text-sm text-gray-500">
            <%= render 'form', product: @product %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6">

  <div class="container m-auto grid grid-cols-2">
    <div class="sm:block">
      <%= form_tag(products_path, method: :get) do %>
        <div class="field">
          <div class="control">
            <div class="field is-medium">
              <%= text_field_tag :query, params[:query], class: 'input is-small', placeholder: 'Search' %>
            </div>
          </div>
        </div>
      <%- end -%>
      <p class="mt-2 text-sm text-gray-700"><%= humanize_product_count(@pagy.count) %></p>
    </div>
    <div>
      <div class="flex flex-1 justify-between sm:justify-end divide-y divide-gray-200">
        <%- if @pagy.next.present? || @pagy.prev.present? %>
          <div class="mt-4 flex justify-center"><%== pagy_nav(@pagy) %></div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">GTIN</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Name</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Brand</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <%- @products.each do |product| -%>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= link_to product.gtin, product_path(product) %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= link_to product.name, product_path(product) %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.brand_name %></td>
              </tr>
              <%- end -%>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6">
  <div class="bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:p-6">
      <div class="sm:flex sm:items-start sm:justify-between">
        <div>
          <h3 class="text-lg font-medium leading-6 text-gray-900">New Product</h3>
          <div class="mt-2 max-w-xl text-sm text-gray-500">
            <%= render 'form', product: @product %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6">
  <div class="bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:p-6">
      <div class="sm:flex sm:items-start sm:justify-between">
        <div>
          <h3 class="text-lg font-medium leading-6 text-gray-900"><%= @product.name %></h3>
          <h2><%= @product.gtin %></h2>
          <div class="mt-2 max-w-xl text-sm text-gray-500">
            <%- if @product.brand_name.present?  %>
              <p><strong>Brand Name</strong> <%= @product.brand_name %></p>
            <%- end -%>
              <%- @product.properties.each do |key, value| -%>
              <p><strong><%= key.humanize %></strong> <%= value %></p>
            <%- end -%>
          </div>
        </div>
        <%- if user_signed_in? -%>
          <div class="mt-5 sm:mt-0 sm:ml-6 sm:flex sm:flex-shrink-0 sm:items-center">
            <%= link_to 'Edit', edit_product_path(@product), class: "inline-flex items-center rounded-md border border-transparent bg-orange-600 px-4 py-2 font-medium text-white shadow-sm hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-2 sm:text-sm" %>
          </div>
        <%- end -%>
      </div>
    </div>
  </div>
</div>