config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # mount Rswag::Ui::Engine => '/api-docs'
  # mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
                     :authorized_applications
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :api, defaults: { format: 'json' } do
    resources :items
  end

  resources :products

  get 'data_license', to: 'home#data_license'
  get 'documentation', to: 'home#documentation'
  get 'acknowledgements', to: 'home#acknowledgements'

  root to: 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="footer-logo">
          <%= image_tag 'barcode-white-large.png', height: '100px' %>
        </div>
      </div>
      <div class="column">
        <div class="footer-column">
          <div class="footer-header">
            <h3>Brocade IO</h3>
          </div>
          <ul class="link-list">
            <li>
              <a href="https://github.com/ferrisoxide/brocade.io">Source Code</a>
            </li>
            <li><%= link_to 'Acknowledgements', acknowledgements_path %></li>
          </ul>
        </div>
      </div>
      <div class="column">
        <div class="footer-column">
          <div class="footer-header">
            <h3>Docs</h3>
          </div>
          <ul class="link-list">
            <li><%= link_to 'API', documentation_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div>
  <div class="mx-auto max-w-7xl px-4 sm:px-6">
    <nav class="relative flex items-center justify-between sm:h-10 md:justify-center" aria-label="Global">
      <div class="flex flex-1 items-center md:absolute md:inset-y-0 md:left-0">
        <div class="flex w-full items-center justify-between md:w-auto">
          <%= link_to root_path do %>
            <span class="sr-only">Brocade.io</span>
            <%= image_tag 'barcode.png', class: "h-8 w-auto sm:h-10", alt: "brocade's logo - a stylised barcode" %>
          <% end %>
          <div class="-mr-2 flex items-center md:hidden">
            <button type="button" class="inline-flex items-center justify-center rounded-md bg-gray-50 p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-orange-500" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <!-- Heroicon name: outline/bars-3 -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
            </button>
          </div>
        </div>
      </div>
      <div class="hidden md:flex md:space-x-10">
        <%= link_to 'Brocade.io', root_path, class: "font-medium text-gray-500 hover:text-gray-900" %>
        <%= link_to 'Products', products_path, class: "font-medium text-gray-500 hover:text-gray-900" %>
        <%- if user_signed_in? -%>
          <%= link_to 'Add Product', new_product_path, class: "font-medium text-gray-500 hover:text-gray-900" %>
        <%- end -%>
        <%= link_to 'Documentation', documentation_path, class: "font-medium text-gray-500 hover:text-gray-900" %>
        <%= link_to 'Github Project', 'https://github.com/ferrisoxide/brocade.io', class: "font-medium text-gray-500 hover:text-gray-900" %>
      </div>
      <div class="hidden md:absolute md:inset-y-0 md:right-0 md:flex md:items-center md:justify-end md:space-x-10">
        <%- if user_signed_in? -%>
          <%= link_to 'My Account', edit_user_registration_path, class: "font-medium text-gray-500 hover:text-gray-900" %>
        <%- end -%>
        <span class="inline-flex rounded-md shadow">
          <% if user_signed_in? %>
            <%=
              button_to(
                'Logout',
                destroy_user_session_path,
                method: :delete,
                class: "inline-flex items-center rounded-md border border-transparent bg-orange-700 px-4 py-2 text-base font-medium text-white hover:bg-orange-800"
              )
            %>
          <% else %>
            <%=
              link_to(
                'Sign in',
                new_user_session_path,
                class: "inline-flex items-center rounded-md border border-transparent bg-orange-700 px-4 py-2 text-base font-medium text-white hover:bg-orange-800"
              )
            %>
          <% end %>
        </span>
      </div>
    </nav>
  </div>

  <!--
    Mobile menu, show/hide based on menu open state.

    Entering: "duration-150 ease-out"
      From: "opacity-0 scale-95"
      To: "opacity-100 scale-100"
    Leaving: "duration-100 ease-in"
      From: "opacity-100 scale-100"
      To: "opacity-0 scale-95"
  -->
  <div class="absolute inset-x-0 top-0 z-10 origin-top-right transform p-2 transition md:hidden">
    <div class="overflow-hidden rounded-lg bg-white shadow-md ring-1 ring-black ring-opacity-5">
      <div class="flex items-center justify-between px-5 pt-4">
        <div>
          <%= image_tag 'barcode.png', class: "h-8 w-auto", alt: "logo"%>
        </div>
        <div class="-mr-2">
          <button type="button" class="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-orange-500">
            <span class="sr-only">Close menu</span>
            <!-- Heroicon name: outline/x-mark -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
      <div class="px-2 pt-2 pb-3">
        <%= link_to 'Brocade.io', root_path, class: "block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900" %>
        <%= link_to 'Products', products_path, class: "block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900" %>
        <%- if user_signed_in? -%>
          <%= link_to 'Add Product', new_product_path, class: "block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900" %>
        <%- end -%>
        <%= link_to 'Documentation', documentation_path, class: "block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900" %>
        <%= link_to 'About', documentation_path, class: "block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900" %>
      </div>
      <% if user_signed_in? %>
        <%= link_to 'My Account', edit_user_registration_path, class: "block w-full bg-gray-50 px-5 py-3 bg-orange-600 text-center font-medium text-white hover:bg-orange-700" %>
        <%=
          button_to(
            'Logout',
            destroy_user_session_path,
            method: :delete,
            class: "block w-full bg-gray-50 px-5 py-3 bg-orange-700 text-center font-medium text-white hover:bg-orange-600"
          )
        %>
      <% else %>
        <%=
          link_to(
            'Sign in',
            new_user_session_path,
            class: "block w-full bg-gray-50 px-5 py-3 bg-orange-700 text-center font-medium text-white hover:bg-orange-600"
          )
        %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_wip_warning.html.erb
<article class="message is-info ">
  <div class="message-body is-size-7">

    <h1 class="title is-size-7">
      Work in Progress
    </h1>
    <p class="is-size-7">
      We're just in the process of setting up this site. Everything will be a bit rough for a while.
    </p>
    <p class="is-size-7">
      Please bear with us while we work through the set up.
    </p>
    <p class="is-size-7">
      If you feel like you might be able to lend a hand - even just to file bug reports / feature requests - head on over to the <a href="https://github.com/ferrisoxide/brocade.io">project page</a> on Github.
    </p>
  </div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-50" lang="en">
  <head>
    <title>Brocade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/favicon' -%>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" data-mutate-approach="sync"></script>
    <%= javascript_importmap_tags %>
  </head>
  <body class="h-full">
    <div class="relative overflow-hidden bg-gray-50">
      <div class="relative pt-6 pb-16 sm:pb-24">
        <%= render 'layouts/navbar' %>
        <%#= render 'layouts/wip_warning' -%>
        <%# NOTE: required by Devise - needs rework %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <%= yield %>
    </div>

  </body>
</html>